# If taking Docker Mastery, this is the same file you created in 
# ./compose-assignment-2
# If taking Swarm Mastery, this is your starting point for adding secrets :)
# reminder, this needs to change to 3.1 version to use secrets!
version: '3.9'

services: 
  drupal:
    image: drupal
    ports: 
      - 8080:80
    volumes:
      - type: volume
        source: modules
        target: /var/www/html/modules
      - type: volume
        source: profiles
        target: /var/www/html/profiles
      - type: volume
        source: themes
        target: /var/www/html/themes
      - type: volume
        source: sites
        target: /var/www/html/sites
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role==manager
    depends_on: 
      - postgres

  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-pw
    volumes: 
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
    secrets:
      - psql-pw
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    
volumes:
  modules:
  profiles:
  themes:
  sites:
  postgres:

secrets:
  psql-pw:
    external: true